# Generated by Django 6.0 on 2025-12-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_address_user_address_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceappeal',
            old_name='class_session',
            new_name='session',
        ),
    ]
