# Generated by Django 6.0 on 2025-12-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classsession_date_classsession_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='student',
        ),
        migrations.AlterField(
            model_name='classsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
