# Generated by Django 6.0 on 2025-12-19 06:38

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_classsession_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_embedding_128',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='face_embedding_512',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
