# Generated by Django 6.0 on 2025-12-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_face_embedding_128_user_face_embedding_512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_embedding_128',
        ),
    ]
