# Generated by Django 6.0 on 2026-01-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='absent_student',
        ),
        migrations.RemoveField(
            model_name='event',
            name='present_student',
        ),
    ]
