# Generated by Django 6.0 on 2026-01-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_classroom_alter_classsession_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_venue', to='core.classroom'),
        ),
    ]
