# Generated by Django 6.0 on 2026-01-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_event_created_at_news_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_embedding_512',
        ),
    ]
