# Generated by Django 6.0 on 2026-01-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_user_face_embedding_512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='student_enrolled',
        ),
    ]
