# Generated by Django 6.0 on 2026-01-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_module_student_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='absent_students',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='attendance_rate',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='present_students',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='total_students',
        ),
    ]
