# Generated by Django 6.0 on 2026-01-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_classsession_absent_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='average_attendance',
        ),
    ]
