# Generated by Django 6.0 on 2026-01-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_module_average_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance_rate',
        ),
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.BooleanField(default=False),
        ),
    ]
