# Generated by Django 6.0 on 2026-01-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_student_attendance_rate_student_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='upcoming', max_length=20),
        ),
    ]
