# Generated by Django 6.0 on 2026-01-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_classsession_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceappeal',
            old_name='document_url',
            new_name='document_path',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='document_url',
            new_name='document_path',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image_url',
            new_name='image_path',
        ),
    ]
