# Generated by Django 6.0 on 2026-01-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_document_url_attendanceappeal_document_path_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['date', 'start_time'], name='core_classs_date_4d1caf_idx'),
        ),
    ]
