# Generated by Django 6.0 on 2026-01-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_classsession_core_classs_date_4d1caf_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendanceappeal',
            index=models.Index(fields=['student', '-created_at'], name='core_attend_student_39ecb1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='core_attend_session_72f03e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student'], name='core_attend_student_4ede38_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['date', 'status'], name='core_classs_date_3ddf61_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['venue', 'date', 'start_time'], name='core_classs_venue_i_15acbb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date', 'status'], name='core_event_event_d_2fe919_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', '-created_at'], name='core_leaver_user_id_47d4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['lecturer', 'status'], name='core_module_lecture_b72e64_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['created_at'], name='core_news_created_1b432c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['start_date', 'end_date'], name='core_semest_start_d_f557fa_idx'),
        ),
    ]
