# Generated by Django 6.0 on 2026-01-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_attendanceappeal_core_attend_student_39ecb1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
