# Generated by Django 6.0 on 2026-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_attendancerecord_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
