# Generated by Django 6.0 on 2026-02-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_attendancerecord_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_student',
        ),
        migrations.AddField(
            model_name='event',
            name='slot_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='events_students', to='core.student'),
        ),
    ]
