# Generated by Django 6.0 on 2026-02-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_event_total_student_event_slot_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='partner_uni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.partneruni'),
            preserve_default=False,
        ),
    ]
