# Generated by Django 6.0 on 2026-02-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_semester_partner_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
